### ISSUE TITLE
README.md Troubleshooting: "Nothing is happening and ksync get says that it is waiting." doesn't make sense.

### ISSUE THREAD

**Issue by dsutphin** [ksync/ksync#231]
https://github.com/vapor-ware/ksync/blob/master/README.md
> # Troubleshooting
>
> - Nothing is happening and `ksync get` says that it is `waiting`.
>
>    This is the state where the cluster is being monitored and it doesn't look like there is anything to do. Make sure you're

This doesn't make sense. Make sure you're what?

**Comment by timfallmk** [comment]
😱 @grampelberg

**Comment by ashahba** [comment]
@dsutphin Are running `ksync` behind `proxy`?

In my case it turned out it was a proxy issue.

**Comment by timfallmk** [comment]
To further clarify, the `waiting` status is the default state. It changes only when matching events are emitted, so we'd probably need more info if you're having a problem.

**Comment by dsutphin** [comment]
@ashahba thank you for the advice but for now I've given up. I just wanted to report the issue with the README.md.

**Comment by timfallmk** [comment]
@dsutphin If you wanted to get started again, feel free to file another issue and we can work through it. Thanks for the headsup!

**Comment by ugoviti** [comment]
Hi, 

I just installed ksync following the README and I'm experiencing the same problem, the `ksync get` return:

          NAME       LOCAL   REMOTE   STATUS    POD   CONTAINER  
    +--------------+-------+--------+---------+-----+-----------+
      clever-mouse   ksync   /code    waiting  

I'm running k8s 1.10.7-gke.1 into GKE env.

ksync is correctly installed:

     $ kubectl get pod -n kube-system -l app=ksync
     NAME          READY     STATUS    RESTARTS   AGE
     ksync-c5jmh   2/2       Running   0          32m
     ksync-l49kg   2/2       Running   0          32m
     ksync-pzblv   2/2       Running   0          32m

Let's me know if you need more info.

Kind regards

**Comment by ugoviti** [comment]
I discovered the cause.

ksync by default search pods on `default` namespace only.

so, even if kubectl is configured to use by default another namespace (`test` in my case) via the command 
`kubectl config set-context $(kubectl config current-context) --namespace=test`, ksync use always the `default` namespace if not specified.

So I workaround this problem with:

`ksync create -n test --selector=app=app $(pwd)/ksync /code`

With kind regards

**Comment by grampelberg** [comment]
That's a great catch @ugoviti, would you mind filing an issue that is separate for that? I didn't know that was even possible!

**Comment by dsutphin** [comment]
@grampelberg You closed this without fixing the README.md. The reason I created this issue. Just a heads up.

**Comment by grampelberg** [comment]
@dsutphin argh, you're totally right. Sorry about that!

**Comment by paullaffitte** [comment]
Someone should update the readme, the missing part is still missing
