### ISSUE TITLE
Switch to use Go Modules?

### ISSUE THREAD

**Issue by timfallmk** [ksync/ksync#253]
Investigate if we should switch to using fancy schmancy new [Go Modules](https://github.com/golang/go/wiki/Modules)

 _heavy sigh_

**Comment by alok87** [comment]
Kubernetes have moved to using Go Modules. The experience is really nice, with it. Should i do it?

**Comment by timfallmk** [comment]
Should be pretty trivial to do this. Go for it.

**Comment by timfallmk** [comment]
Closed by #317
