### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by sdaschner** [ksync/ksync#289]
Both `ksync init` and `ksync doctor` fail with the following error: `rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

However, `docker ps` works, I can connect Docker containers to the Docker host by mounting `/var/run/docker.sock`, and the current user is in the `docker` group.

More information:

```
$> docker version
Client:
 Version:           18.09.5-ce
 API version:       1.39
 Go version:        go1.12.3
 Git commit:        e8ff056dbc
 Built:             Fri Apr 12 08:22:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.3
  Git commit:       e8ff056dbc
  Built:            Fri Apr 12 08:21:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$> ksync version
ksync:
	Version:    Release
	Go Version: go1.12.1
	Git Commit: c27ce95
	Git Tag:    0.3.6
	Built:      Mon Mar 18 17:06:42 +0000 2019
	OS/Arch:    linux/amd64
service:
	Version:    Release
	Go Version: go1.12.1
	Git Commit: c27ce95
	Git Tag:    0.3.6
	Built:      Mon Mar 18 17:02:16 +0000 2019

$> ls -ahl /var/run/docker.sock
srw-rw---- 1 root docker 0 Apr 30 06:12 /var/run/docker.sock

$> ksync doctor
Extra Binaries                              ✓
Cluster Config                              ✓
Cluster Connection                          ✓
Cluster Version                             ✓
Cluster Permissions                         ✓
Cluster Service                             ✓
Service Health                              ✓
Service Version                             ✓
Docker Version                              X
	rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I've installed `ksync` using the `gimme.sh` script.

**Comment by timfallmk** [comment]
While you can change the docker socket location, the default should work. Try `sudo ksync doctor` and see if that gives you a different result.

**Comment by sdaschner** [comment]
No, unfortunately that also doesn't work. Sorry, forgot to mention, that I've tried that already as well.

**Comment by sdaschner** [comment]
Do you have any other ideas? This renders the tool unusable for me unfortunately :(

**Comment by timfallmk** [comment]
Ping @grampelberg

**Comment by fkaleo** [comment]
I had a similar issue when using the git master version of kind (kubernetes in docker) which removed docker entirely from the pods. Reverting to the last release fixed it.

**Comment by sdaschner** [comment]
My k8s cluster is running containerd as runtime (IBM K8s service, on `1.12.7_1548`), is that the issue?

Does the `Docker Version` check the cluster or the local Docker host?

**Comment by timfallmk** [comment]
Docker version checks both IIRC. There may be a special configuration that IBM is using though that isn't checked. Maybe the user it's running as doesn't have access to the daemon.

**Comment by sdaschner** [comment]
Access to which daemon? The one on the local Docker host? I have access to this.

Do you have some further information or ideas how to debug this?

**Comment by timfallmk** [comment]
is the user you're running `ksync` under able to access docker?

It's literally running the equivalent of `docker version` against the API there, so any difference in results between those two commands would be down to configuration differences. Perhaps there is some difference between how your docker client is configured and the default options.

**Comment by sdaschner** [comment]
Yes, it is. Good questions... I've seen cases before where at an outdated version of a Docker API (that was using docker-java) resulted in a error since it didn't understand a newer Docker config format. I'll look into that with a new Docker installation...

**Comment by samgabrail** [comment]
I have the same issue and I'm running containerd as the run-time. Docker commands show that it isn't installed on the host. Is there support for containerd?

**Comment by grampelberg** [comment]
@samgabrail unfortunately not today. We'd love help adding it, but it'd be non-trivial I'm afraid.

**Comment by optimus-kart** [comment]
Guys are there any workarounds for this?

**Comment by grampelberg** [comment]
@optimus-kart would love the help adding support!

**Comment by grampelberg** [comment]
There's no guide, I'd recommend getting into the code and understanding how all the pieces fit together. Instead of putting a driver in place for containerd, I'd actually recommend a larger refactor to start using [shared pid](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) and [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/).

**Comment by optimus-kart** [comment]
@grampelberg sure, let me dig into the code and see what can be done, will keep you posted

**Comment by retr0h** [comment]
@optimus-kart any news on this?
