### ISSUE TITLE
Making ksync work in a RBAC enabled internal cluster with public k8s elb

### ISSUE THREAD

**Issue by alok87** [ksync/ksync#294]
There could be two kinds of users for ksync.

1. Users having their own kubernetes cluster with the cluster machine being publically accesible
2. Users having namespaced/or limited access to a kubernetes cluster. Basically a users sharing a single kubernetes cluster using RBAC. Also these users have a cluster which is internal and only the kuberentes api loadbalancer is public.

ksync works perfectly when you fall into first kind of users. But from what i have experienced so far, code is not friendly for second type of users https://github.com/vapor-ware/ksync/issues/293  

I would like to contribute to ksync to make it friendly for 2nd kind of user. I see there are the areas of work here
1) to make it RBAC friendly with every access configured at the time of installation.
2) to make it workable for clusters in which nodes are internal and api server is only public. Will tunnelling work? will sync work in this kind of setup?

What are the things that is required to be changed? Will it be a major work?

@timfallmk @grampelberg please help me do this. We want to use ksync :)

**Comment by alok87** [comment]
Trying to make `ksync watch`. Stuck here.

```
next: pods is forbidden: User "alok.singh@practo.com" cannot list resource "pods" in API group "" in the namespace "kube-system"
```

What role is required for this, as API Group is showing ""

**Comment by timfallmk** [comment]
Off the top of my head, it would take some doing to get this working. The main problem you would have is that currently `ksync` needs administrative access to the docker daemon (in order to interact with the filesystems and event streams), which essentially gives a user unrestricted access to all containers run on that node.

**Comment by alok87** [comment]
@timfallmk I can help in contributing. If you could break it down into multiple tasks.

**Comment by alok87** [comment]
This can be used as a referrence for people facing issues. Nothing to do here extra. closing this.
