### ISSUE TITLE
Ksync copy should copy with default container user

### ISSUE THREAD

**Issue by alok87** [ksync/ksync#296]
Docker container has the default user `docker` but it is changing to `root` on copying the files from local to the remote container.

We are facing an issue in which the file from local gets copied as the `root` user and the application needs the file to be docker user.

**Comment by timfallmk** [comment]
I'm not quite following. The file is owned by `root` on the local side, but it needs to be owned by a different user on the remote side?

**Comment by alok87** [comment]
So the docker image has a a different user (`docker`) as the default user. When the file is copied from local to remote instead of having the user as `docker` it is changing the file to have `root`. 
Nothing to do with local.

**Comment by koxu1996** [comment]
Synthing v1.1.0 [introduced](https://github.com/syncthing/syncthing/commit/75dcff0a0e7fe7afc25492588370f23f8075c8fa) folder option _CopyOwnershipFromParent_ that allow to retain the owner/group information if possible. Currently I don't know _Golang_ much, so I won't prepare PR, however I was able to recompile _ksync_ with this option enabled:
```
(host)$ mkdir ksync
(host)$ docker run -it -v $PWD/ksync:/host circleci/golang bash
(host)$ go get -v github.com/vapor-ware/ksync/...
$ cd /go/src/github.com/vapor-ware/ksync
$ go get -v github.com/golang/dep/cmd/dep
$ go install github.com/golang/dep/cmd/dep
$ dep ensure -v --vendor-only
$ dep ensure -v -update github.com/syncthing/syncthing
$ sed -i 's/\(folder.FSWatcherEnabled = true\)/\1\n\tfolder.CopyOwnershipFromParent = true/' ./pkg/syncthing/folder.go
$ make build-ci OPTS='-os="!netbsd !freebsd !openbsd" -arch="amd64"'
$ sudo cp bin/* /host/
$ exit
(host)$ sudo cp ksync/ksync_linux_amd64 /usr/local/bin/ksync
(host)$ rm -rf ksync
```
I think such option should be always enabled, but you can also make it configurable. It works for me well.

**Comment by igoooor** [comment]
Do we have any news on this?

**Comment by timfallmk** [comment]
Interesting. Looks like it's on us to fix. I'm currently on vacation, but it shouldn't be too hard to change, as @koxu1996 noted (thanks for that!).

**Comment by timfallmk** [comment]
@grampelberg Side note, this requires a newer version of syncthing than we current vendor.

**Comment by grampelberg** [comment]
Would love a PR for this! Now that the CI stuff is setup and mostly working again, it would be easy to cut a new stable release and fix the tagging issues as well once it lands.
