### ISSUE TITLE
--pod and -p don't select a single pod 

### ISSUE THREAD

**Issue by robert-burden** [ksync/ksync#297]
I have a replica set with several with two pods. No matter what I try I cannot make ksync only select a specific pod. 

Following the readme I tried:
`ksync create --name test --pod api-server-7d48bfc846-2zdg8 /local/scripts/ /pod/scripts`
- This seems to completely ignore the --pod parameter and try to connect to all pods in the namespace.

`ksync create --name test --pod api-server-7d48bfc846-2zdg8 -c api-server /local/scripts/ /pod/scripts`
- This selects all the pods using the `api-server` container which is better because it selects only the two identical pods but ideally I would only want to sync with one. 

I have also tried adding "quotes" around the name and setting up the key/value pair like --pod=api-server with identical results

**Comment by alok87** [comment]
Best is to do this.

1) First edit the pod and see what labels it has
`kubectl edit pod api-server-7d48bfc846-2zdg8`

2) Try to list the pods using kubectl  first
`kubectl get pods -n <namespace> -l type=api -l app=api-server`

If this list your pod. Then create the ksync configuration using same label selectors(`-l`).
3) `ksync create --name test  -l type=api -l app=api-server /local/scripts/ /pod/scripts`


I have not used `pods` yet as label selectors works perfectly as i want and is better than pod option as pod names can keep changing.

**Comment by robert-burden** [comment]
@alok87 I doubt there is a combination of label selectors that will result in selecting a single specific pod from a replica set. There are many cases where someone would want to sync specifically with a pod for the lifecycle of that pod. 

I am sure I can work around this for my use case. The purpose of this issue is to note that the flag doesn't work as advertised and should probably be removed from the first step of the README if its not the recommended way of selecting a single pod. 

> 1) `ksync create --pod=my-pod local_directory remote_directory` to configure a folder you'd like to sync between your local system and a specific container running on the cluster.

**Comment by timfallmk** [comment]
I don't think I've seen someone use that flag before, so I'll take a look shortly to see what it's doing.

**Comment by AndrienkoAleksandr** [comment]
+1  saw the same. It works good when I set up pod '-p' and container '-c', but if I set up only pod -p -> seems ksync trying to watch all pods.

**Comment by grampelberg** [comment]
Interesting, definitely a bug in there somewhere.

**Comment by provAlexSage** [comment]
This is because the flag format doesn't accept the space and needs the equal sign...
```bash
ksync create --name test --pod=api-server-7d48bfc846-2zdg8 -c api-server /local/scripts/ /pod/scripts
```

**Comment by timfallmk** [comment]
I'm going to mark this as solved. Thanks everyone!
