### ISSUE TITLE
Cannot get past the waiting state

### ISSUE THREAD

**Issue by jamespedid** [ksync/ksync#298]
Hello, I cannot get past the waiting state for a pod. Kubernetes is deployed via docker-for-desktop.

I have a kubernetes deployment with the following label for the containers. Containers are deployed to the default namespace.
```
com.name.devprod.service: myservice
```

I followed the guide and I ran the ksync init and watch. According to the doctor everything is good.

Now when I use the following a spec is created
```
ksync create -l "com.name.devprod.service=myservice"
```

However the state never changes from waiting. What am I missing? I also tried using a pod name directly, and that did not work either.

**Comment by alok87** [comment]
`ksync` create will only create the configuration requried to sync in `~/.ksync.yaml`


1) Try to list the pods using kubectl, it it shows up try 2 otherwise debug why it is not showing.
```bash
kubectl get pods -l "com.name.devprod.service=myservice"
```
2) Run `ksync` watch to start the sync

**Comment by jamespedid** [comment]
Already did all of those things multiple times. The only thing I can think of is that it installed incorrectly somehow.

**Comment by timfallmk** [comment]
Usually that means it didn't get the "sync complete" response message it expected from the remote end. It may be helpful to nuke it and run again with debug logging on to see if something stands out.
