### ISSUE TITLE
Downloading 0.4.0 from github release - showing corrupt

### ISSUE THREAD

**Issue by alok87** [ksync/ksync#320]
```
$ ./ksync_darwin_amd64 version
ksync:
	Version:    corrupted-version
	Go Version: go1.13.1
	Git Commit: dcb80e9
	Git Tag:
	Built:      Thu Oct 17 22:39:47 +0000 2019
	OS/Arch:    darwin/amd64
service:
	Version:    Release
	Go Version: go1.12.1
	Git Commit: c27ce95
	Git Tag:    0.3.6
	Built:      Mon Mar 18 17:02:16 +0000 2019

```

**Comment by grampelberg** [comment]
@timfallmk this is because I didn't build with the tag? Sounds like the github actions stuff missed a couple pieces.

**Comment by timfallmk** [comment]
Yeah, it wouldn’t be sourced during the build. Might be worth rebuilding when we release to get the stamps.

**Comment by alok87** [comment]
Is this fixed? can we download the latest release now?

**Comment by timfallmk** [comment]
@alok87 you should be fine running the current binary. The release just failed to be stamped and therefore has the default version string. We’ll try and fix the stamping issue soon, but there should be no changes to the binary.
