### ISSUE TITLE
Images for release 0.4.0 missing on dockerhub

### ISSUE THREAD

**Issue by markus512** [ksync/ksync#323]
Tried to install release 0.4.0 onto my kubernetes cluster.

Pods don't start because tag 0.4.0 is missing in vaporio/ksync on dockerhub.

I replaced the image with ksync/ksync:git-11c5444 which seems to work fine but it would be great if it is possible to upload that tag and make release 0.4.0 working as is.

**Comment by grampelberg** [comment]
How are you running 0.4? I just double checked and it is using `ksync/ksync:git-dcb80e9` by default.

**Comment by markus512** [comment]
I tried to install it from jenkins x using jx sync. Will try to debug that tomorrow. Manual installation indeed works as usual and uses ksync/ksync:git-dcb80e9.

**Comment by markus512** [comment]
I'll close this issue now as there is nothing wrong in ksync itself.
@grampelberg Thank you for taking the time to deal with my issue.

**Comment by grampelberg** [comment]
You bet! Sorry about the extra overhead there from the org change.
