### ISSUE TITLE
Ksync keeps crashing 

### ISSUE THREAD

**Issue by alok87** [ksync/ksync#334]
We are facing this issue across the organization with the latest ksync version also. (`0.4.3`)
There are two issues here.

1. ksync crashes very frequently. Almost after sometime.
`panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod`
```
INFO[0012] updating                                      pod=voice-20200219-120234-67b8959787-npsbd spec=voicespec
INFO[0012] update complete                               pod=voice-20200219-120234-67b8959787-npsbd spec=voicespec
panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod
```

2. When it crashes(exits 1), it keeps running the syncthing command in the background. So the next start also gets stuck. So we need to kill the process manually and then start it again.
```
$ ksync watch
INFO[0001] listening                                     bind=127.0.0.1 port=40322
INFO[0001] syncthing listening                           port=8384 syncthing=localhost
INFO[0001] new pod detected                              pod=voice-20200219-120234-67b8959787-npsbd spec=voicespec
FATA[0002] Something is running on 8384 (run 'lsof -i :8384' to find out). Please stop that process before continuing.
```

Really want to fix this with ksync. It becomes really difficult to work locally when these problems are quite frequent.

Any pointers on how to go about debugging this issue and finding its root cause.

**Comment by grampelberg** [comment]
Have you tried rolling back to 0.4.2? We did some dependency updates in 0.4.3 and that was it.

**Comment by alok87** [comment]
It was happening in 0.4.2, and then i upgraded to 0.4.3 and issues was happening in both the places.
I am not sure if it is a connection issue. Changing the subject of the issue.

**Comment by grampelberg** [comment]
Ahh, have you changed anything in your cluster?

**Comment by alok87** [comment]
@grampelberg no, we have created a default cluster with kops, its version is 1.15.5
How to debug the issue, it just says panic but no line info as such. How can I reproduce this with code line info in my local?

**Comment by grampelberg** [comment]
`panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod` makes me think your API server is totally returning the wrong results entirely. Bumping up the debugging and adding some logging in there would help a ton. Maybe do a reflection?

**Comment by alok87** [comment]
Its Kubernetes API 15.5.5? Where should i add logging? Can you point out the exact code line in ksync which is calling kubernetes API?

**Comment by alok87** [comment]
Ok, here is the trace

**Comment by alok87** [comment]
@grampelberg I did the reflect type to find the event type received. Here is the code i changed 
```
 func (s *Spec) handleEvent(event watch.Event) error {
+       fmt.Printf("event: %v\n", event)
+       fmt.Printf("reflect.TypeOf(event): %v\n", reflect.TypeOf(event))
```

Here is the output i got
```
event: {ERROR &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR") has prevented the request from succeeding,Reason:InternalError,Details:&StatusDetails{Name:,Group:,Kind:,Causes:[]StatusCause{StatusCause{Type:UnexpectedServerResponse,Message:unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR,Field:,},StatusCause{Type:ClientWatchDecoding,Message:unable to decode an event from the watch stream: stream error: stream ID 1; INTERNAL_ERROR,Field:,},},RetryAfterSeconds:0,UID:,},Code:500,}}
reflect.TypeOf(event): watch.Event
panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod
```
