### ISSUE TITLE
Ksync watcher should reestablish connection

### ISSUE THREAD

**Issue by alok87** [ksync/ksync#337]
At present ksync watcher does not reestablish connection when the [event channel receives nil](https://github.com/ksync/ksync/blob/dcb80e9f58dcec10ce4c1356ab88fbbd4f862958/pkg/ksync/spec.go#L125-L133), we are using a higher level service to restart ksync on such failures.

We can make watcher restablish connections after some time if it receives a empty channel. Kubernetes API is timebound and we see this happening at fixed intervals only(every few minutes - will tell the exact no.os after test).

Slack discussion on this:  https://kubernetes.slack.com/archives/C0EG7JC6T/p1582204821408400

This can be done by using https://github.com/kubernetes/client-go/blob/master/tools/watch/informerwatcher.go

cc 🎩@liggitt  @grampelberg

**Comment by alok87** [comment]
Below are the observations for the ksync crashing after every few minutes.

### Crash is happening every 1minute 40seconds
Ksync is crashing in about 2minutes. I am running **`date && ksync watch || date`** to note the timings of crash.  Here are the results:

- Run1: 1 min40sec  Thu Feb 20 20:45:36 IST 2020 --> Thu Feb 20 20:47:16 IST 2020  
- Run2: 1 min40sec  Thu Feb 20 20:49:04 IST 2020 --> Thu Feb 20 20:50:44 IST 2020

### Issue is independent of ksync client version or network
Issue is happening from both office and home wifi network for many people.

**Comment by grampelberg** [comment]
If your k8s cluster is returning 500s every 1m40s, there's probably something *much* more fundamentally wrong going on. I would recommend looking in the logs and figuring out what is going on there first before looking any further into ksync itself. I would also try and reduce the links in the problem - try running ksync from inside the cluster to rule out any kind of connectivity issue and see if it still happens. With the timing being so precise (and me being unable to replicate this at all), it is entirely possible you've got something in the chain that is cutting the connection off.

It follows that I don't feel confident that using an InformerWatcher would solve the issue. It is more likely to paper over an underlying issue. For example, there's also a port-forward going on in the background. If your API server is throwing 500s (which is concerning), I would be worried that the port-forward would also get shut down.

All that said, doesn't look too hard to update everything over to the new method. I'd love to see a PR on it if you're up for it!

**Comment by alok87** [comment]
@grampelberg will work on the following
- [ ] Finding the reason for 100 second timeout.
- [ ] Finding the 500 in k8s events
- [ ] Will give the PR to use informer

**Comment by grampelberg** [comment]
@alok87 that's awesome, thank you! I'm happy to help however I can.

**Comment by alok87** [comment]
The 100 second timeout was because Cloudflare has a 100 second default timeout between Cloudflare and the origin (ELB in our case). I have got it increased and now ksync will crash after an increased minute. Marking first as done.

**Comment by grampelberg** [comment]
You know, if it is 20 minutes, you might want to fix this by having the `syncthing` process correctly reaped when the parent exits instead of going down the informer route. The reasoning there is that the port-forward is going to die, which'll be the next thing you need to manage disconnects/reconnects on.

**Comment by grampelberg** [comment]
For future reference, this was caused because of a timeout introduced by a load balancer in the middle. Ksync shuts down on connection issues on purpose. This is because it is hard to have all the required connections restarted gracefully. Errors like this should be managed either by removing the intermediate timeout or with an external process manager which restarts ksync. Failing fast allows for the system to restart gracefully.
