### ISSUE TITLE
No service account prevent configuring pod security policy

### ISSUE THREAD

**Issue by mlitvin** [ksync/ksync#341]
The ksync daemonset require non-trivial PSP: ability to mount hostPath. But because the daemon set doesn't use a service account it is impossible to grant that permission specifically and it should be granted by default.

The first level of a solution would be creation and usage of  a service account for ksync.

A nice to have would be an option to create (and bind) the PSP from sync init

**Comment by grampelberg** [comment]
Good call! Up for a PR? Might as well just create the SA and PSP at the same time.

**Comment by grampelberg** [comment]
You'd need to modify https://github.com/ksync/ksync/blob/master/pkg/ksync/cluster/daemon_set.go#L14 and:

- Make it a list instead of a DaemonSet.
- Add the SA and PSP in there.

**Comment by moshelitvin-MS** [comment]
I can give it a try
