### ISSUE TITLE
Sync With Kubernetes Persistent Volume

### ISSUE THREAD

**Issue by sergioska** [ksync/ksync#378]
When i try to sync a local path with a kubernetes persistent volume at the end of the sync process i don't see files on container.
Sync process seems run fine because i can see it on web gui, but at the end directory on cluster is empty.
If i try to run sync operation without persistent volume directly on a path of container, it works fine.

**Comment by timfallmk** [comment]
Hi @sergioska . `ksync` only works with Docker defined and managed volumes at the moment, so it won't work with PVS's unfortunately.

**Comment by grampelberg** [comment]
@sergioska we'd love help making it work with volumes if you're up for it! There's a new arch that uses shared pid namespace and ephemeral containers to make the whole thing *way* more stable.
