### ISSUE TITLE
Ksync is  forbidden

### ISSUE THREAD

**Issue by hansongfang** [ksync/ksync#398]
After installation, I check the ksync version and get this error apps ksync is forbidden". I tried searching previous issues, but not found a solution. Your help is appreciate!
$ ksync version
ksync:
        Version:    Release
        Go Version: go1.13.6
        Git Commit: b2ca492
        Git Tag:    0.4.4
        Built:      Thu Feb 20 23:22:28 +0000 2020
        OS/Arch:    darwin/amd64
FATA[0000] daemonsets.apps "ksync" is forbidden: User "http://cilogon.org/serverA/users/18356311" cannot get resource "daemonsets" in API group "apps" in the namespace "kube-system"

**Comment by grampelberg** [comment]
That means your RBAC isn't working correctly. You need to get able to get `daemonsets` in the `kube-system` namespace.
