### ISSUE TITLE
ksync init failing on mac

### ISSUE THREAD

**Issue by ryneal** [ksync/ksync#409]
ksync init is failing to run, stating invalid tar header for syncthing binary.

I am unable to determine the cause, and have no specific networking configuration such as proxies.

Can anyone please advise how I can resolve this issue?

Output of ksync init --log-level trace

```
ksync init --log-level trace
DEBU[0000] initializing kubernetes client                context=
DEBU[0000] kubernetes client created                     host="<excluded>"
==== Local Environment ====
DEBU[0000] fetching new syncthing binary
DEBU[0003] found binary
DEBU[0003] decompressing
Fetching extra binaries                     ✘
↳	archive/tar: invalid tar header
FATA[0003]
```

Output of ksync version
```
ksync version
ksync:
	Version:    Release
	Go Version: go1.13.6
	Git Commit: b2ca492
	Git Tag:    0.4.4
	Built:      Thu Feb 20 23:22:28 GMT 2020
	OS/Arch:    darwin/amd64
```

**Comment by timfallmk** [comment]
Is this a fresh install? Did it just start happening?

**Comment by timfallmk** [comment]
It 👀 like github.com/syncthing/syncthing at some point changed _only_ the macOS binary from a tar gzip to a zip format. I'm gonna do some more poking around to see if this was intentional or not, in the meantime @ryneal, you can download, extract and place the binary manually (I believe the default install directory is `~/.ksync/bin` but I'm not sure)

**Comment by timfallmk** [comment]
The upstream issue appears to have come from [here](https://github.com/syncthing/syncthing/commit/d8e7e92512d703d5e4f644b3104e248e9e615b0c). On first glance it shouldn't take too much work to fix.

**Comment by jaiwo99** [comment]
I have the same issue: 

ksync:
	Version:    Release
	Go Version: go1.13.6
	Git Commit: b2ca492
	Git Tag:    0.4.4
	Built:      Thu Feb 20 23:22:28 +0000 2020
	OS/Arch:    darwin/amd64
INFO[0000] Remote service is not running. Run init to start it.
FATA[0000] no healthy nodes found
exit 1

DEBU[0000] initializing kubernetes client                context=
DEBU[0000] kubernetes client created                     host="<host>"
==== Local Environment ====
DEBU[0000] fetching new syncthing binary
DEBU[0001] found binary
DEBU[0001] decompressing
Fetching extra binaries                     ✘
↳	archive/tar: invalid tar header
