### ISSUE TITLE
Ksync init doesn't support specifying a kubeconfig file to talk to remote cluster 

### ISSUE THREAD

**Issue by buptliuwei** [ksync/ksync#445]
Hi all,
In my platform, i specify other kubeconfig files by setting the `--kubeconfig` flag to access k8s cluster. when i try to  Initialize ksync with command `ksync init --context string`,  the ksync client will get `kubeconfig` file from  `$HOME/.kube` or `KUBECONFIG` environment variable. 
So, during ksync init, can we also specify other kubeconfig files by setting  `--kubeconfig` flag. Jsut look like 
```
ksync init --context xxx --kubeconfig xxx
```

I refer to the documentation: [Organizing Cluster Access Using kubeconfig Files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/)
I raised this issue because of my own usage style and some confusion. If someone has discussed before and thinks this feature is not needed, please ignore this ：）

**Comment by timfallmk** [comment]
You can specify the kubeconfig file location with the env variable, as per other kube related tools.
Something like:
```shell
KUBECONFIG=/some/path ksync doctor
```
