### ISSUE TITLE
0.4.6 retagged?

### ISSUE THREAD

**Issue by carlocab** [ksync/ksync#495]
When Homebrew [updated ksync to 0.4.6](https://github.com/Homebrew/homebrew-core/pull/70653), the sha was recorded as a63f23dba397a540cca9cbde5001afa5cbd8b2ae. However, it seems 0.4.6 has been retagged to bfb445b179a0405ab4a01b999010010406f425b7.

I can update the hash in the Homebrew formula, however, I'd like to double-check that this was intentional and that nothing's amiss here. Thanks!

**Comment by timfallmk** [comment]
It was likely intentional, although I don't personally remember. I have re-pushed tags before when a release mechanism was changed/didn't work. Sorry about that!

**Comment by carlocab** [comment]
I see, thanks for clarifying.

It would help if you just tagged new versions. The [git docs](https://git-scm.com/docs/git-tag#_on_re_tagging) even describe re-tagging as the "insane" thing to do.

**Comment by timfallmk** [comment]
@carlocab It is yes. While this project was under active development it was the only way that we could test release processes without spinning several hundred new tags. Nowadays re-tagging will be avoided if at all possible.
