### ISSUE TITLE
Discussion forum for ksync project

### ISSUE THREAD

**Issue by manning-ncsa** [ksync/ksync#539]
Is there a discussion forum for ksync? I do not see any references in the docs and I cannot find one in the usual places (IRC, Matrix, Discourse site from general web search). If there is not one, I recommend claiming some Matrix rooms like `#ksync-dev:matrix.org`. In fact, I just created a room for the purpose at [#ksync-general:matrix.org](https://matrix.to/#/#ksync-general:matrix.org), for which I will transfer admin privileges to the ksync project leaders (@timfallmk) at their request.

**Comment by timfallmk** [comment]
This seems like a great idea. Unfortunately, as many people have noticed, @grampelberg and myself have both become involved in other things and this project has fallen by the wayside. I would be more than happy if you wanted to create and control spaces to discuss it. We've even discussed seeking a new maintainer(s) for the project.

**Comment by manning-ncsa** [comment]
Shortly after creating this issue and failing to get ksync to work consistently (e.g. the initial file sync would work but then subsequent file updates were never synced), I discovered [Okteto](https://okteto.com/), which works well for our needs. Good luck with your current and future endeavors.
