### ISSUE TITLE
ksync becoming unusable with modern k8s clusters due to deprecation of docker in favour of containerd

### ISSUE THREAD

**Issue by ineffyble** [ksync/ksync#547]
Kubernetes [officially deprecated Docker as a container runtime](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) in k8s 1.20, in favour of containerd directly.

As a result, modern k8s clusters are starting to be built with containerd (for example, kops 1.20+ uses containerd as runtime by default to match the Kubernetes change). 

As has been stated in various other issues such as #327 #289 this breaks ksync, which requires Docker currently.

**Comment by danwilxite** [comment]
+1
Docker runtime has now been removed in 1.22, so ksync can no longer work with the latest kubernetes versions.

**Comment by timfallmk** [comment]
This project is largely defunct due to this and both creators moving on.
