### ISSUE TITLE
Can ksync update a failed or completed kubernetes job?

### ISSUE THREAD

**Issue by apatil4** [ksync/ksync#549]
I am using an EKS cluster and been running ML experiments using Kubernetes jobs. A job brings up a pod that runs the ML experiment which can take a day or two. What we want is the pod fails or completes, we want to update the code and restart the experiment from start. 
However, seems like the pod needs to be running for the ksync to update the live code. Is that correct?
**Note: A job does not clean up a failed or completed pod so it is available for update if that can happen.**

**Comment by timfallmk** [comment]
This depends on how the data is stored for the target pod. Ksync doesn't actually do anything with the pods themselves, only access their volumes. If the data is stored separately it can be accessed anytime.

Pro-tip. You can always get a pod to "run" by exec-ing a long running command into it, i.e. `sleep 1000`, giving you enough time to access it.
