### ISSUE TITLE
ksync triggering browser reloads

### ISSUE THREAD

**Issue by neahan** [ksync/ksync#554]
is there a (easy) way to get kysnc to trigger a local browser to reload after files has been transfered to a pod.

I tried setting up my own system (get ksync to output to a log file, then gulp. js to watch it for changes, then browserSync to reload the browser) but it didn't work very well.

**Comment by timfallmk** [comment]
I'm not sure there would other than maybe watching for `fsevents` for the data you're working on. Alternatively the `syncthing` logs might be useful.
